set(_MINECRAFT_WORLD_DURANGO_NET_MINECRAFT_STATS
  "${CMAKE_CURRENT_SOURCE_DIR}/DurangoStats.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/DurangoStats.h"
)
source_group("net/minecraft/stats" FILES ${_MINECRAFT_WORLD_DURANGO_NET_MINECRAFT_STATS})

set(MINECRAFT_WORLD_DURANGO
  ${_MINECRAFT_WORLD_DURANGO_NET_MINECRAFT_STATS}
)
