name: Build Minecraft Legacy Console Edition
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        configuration: [Release, Debug]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Minecraft Legacy Console Edition
        run: |
          msbuild MinecraftConsoles.sln `
            /p:Configuration=${{ matrix.configuration }} `
            /p:Platform=Windows64 `
            /m
                  
      - name: Upload Release + Debug Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MinecraftClient-${{ matrix.configuration }}
          path: x64/${{ matrix.configuration }}
