name: Nightly Release

on:
  workflow_dispatch: 
  push:
    branches:
    - 'main'

jobs:
  build:
    name: Build Windows64
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v2
    
    - name: Build
      run: MSBuild.exe MinecraftConsoles.sln /p:Configuration=Release /p:Platform="Windows64"