name: Pull Request Build

on:
  workflow_dispatch: 
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - '.gitignore'
      - '*.md'
      - '.github/*.md'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup CMake
      uses: lukka/get-cmake@latest
    
    - name: Run CMake
      uses: lukka/run-cmake@v10
      env:
        VCPKG_ROOT: "" # Disable vcpkg for CI builds
      with:
        configurePreset: windows64
        buildPreset: windows64-debug
